version: '3'

services:
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    expose:
      - "8000"
    volumes:
      - static_volume:/usr/src/app/jobs/staticfiles
    #    env_file: .env
    command: gunicorn jobs.wsgi:application --bind 0.0.0.0:8000

  nginx:
    restart: always
    build: ./deployment/nginx/
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/jobs/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
