import factory
from typing import Any

class UserFactory(factory.django.DjangoModelFactory):  # type: ignore
    class Meta:
        model: Any = ...
        django_get_or_create: Any = ...
    first_name: str = ...
    last_name: str = ...

class JobFactory(factory.django.DjangoModelFactory):  # type: ignore
    class Meta:
        model: Any = ...
        django_get_or_create: str = ...
    user: Any = ...
    title: str = ...
    description: str = ...
    type: str = ...
