# Generated by Django 4.0.1 on 2022-03-28 14:54

from django.db import migrations, models
import resume_cv.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cv', '0003_resumecvtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecvcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=resume_cv.models.resume_cv_directory_path),
        ),
    ]
