# Generated by Django 4.0.1 on 2022-04-19 14:43

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_cv', '0004_alter_resumecvcategory_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecv',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resume_cvs', to='resume_cv.resumecvtemplate'),
            preserve_default=False,
        ),
    ]
