{
 "title": "Device",
 "tags": [ "linux" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu))"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"})"
    },
    {
     "expr": "sum(node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"})"
    },
    {
     "expr": "sum(node_time_seconds{instance=~\"$instance\",job=~\"$job\"} - node_boot_time_seconds{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Sys Load",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_load1{instance=~\"$instance\",job=~\"$job\"})"
    },
    {
     "expr": "sum(node_load5{instance=~\"$instance\",job=~\"$job\"})"
    },
    {
     "expr": "sum(node_load15{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "100 - (( sum(node_filesystem_avail_bytes{instance=~\"$instance\",job=~\"$job\", fstype=~\"ext4|ext3\"}) by (device) * 100) / sum(node_filesystem_size_bytes{instance=~\"$instance\",job=~\"$job\", fstype=~\"ext4|ext3\"}) by (device))"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance\",job=~\"$job\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (5 min average)",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "avg(node_load5{instance=~\"$instance\",job=~\"$job\"}) /  count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$instance\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$instance\",job=~\"$job\"}) / (node_memory_SwapTotal_bytes{instance=~\"$instance\",job=~\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (instance, cpu)) by (instance)) - sum(sum(irate(node_cpu_seconds_total{mode='idle',instance=~\"$instance\",job=~\"$job\"}[5m])) by (mode, instance)) by (instance) ) * 100) / count(count(node_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}) by (instance, cpu)) by (instance)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"} - node_memory_MemAvailable_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~\"$instance\",job=~\"$job\"}[5m])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  }
 ]
}