# Generated by Django 5.1.2 on 2026-04-28 18:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=160, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=150, null=True)),
                ('size', models.CharField(blank=True, choices=[('1', '1-10 employees'), ('2', '11-50 employees'), ('3', '51-200 employees'), ('4', '201-500 employees'), ('5', '501-1000 employees'), ('6', '1000+ employees')], max_length=20)),
                ('culture_benefits', models.TextField(blank=True, help_text='Describe company culture, benefits, and perks', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Feature this company on the homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='company_covers/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=340)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], max_length=10)),
                ('workplace_type', models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry level'), ('mid', 'Mid level'), ('senior', 'Senior level'), ('lead', 'Lead/Staff')], default='entry', max_length=20)),
                ('application_deadline', models.DateTimeField()),
                ('website', models.URLField(blank=True, help_text='Optional external apply URL', max_length=300, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=20)),
                ('salary', models.IntegerField(blank=True, default=0)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='BDT', max_length=5)),
                ('salary_period', models.CharField(choices=[('month', 'Per month'), ('year', 'Per year'), ('hour', 'Per hour')], default='month', max_length=10)),
                ('vacancy', models.IntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobsapp.company')),
                ('tags', models.ManyToManyField(to='tags.tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('soft_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='jobsapp.job')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobsapp.job')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_company_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'filled'], name='jobsapp_job_status_88565f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['type', 'workplace_type'], name='jobsapp_job_type_b00a27_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['created_at'], name='jobsapp_job_created_bcca72_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['application_deadline'], name='jobsapp_job_applica_564e1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('user', 'job')},
        ),
    ]
