# Generated by Django 3.0.7 on 2020-08-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190326_1754'),
        ('jobsapp', '0007_job_salary'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('user', 'job')},
        ),
    ]
