# Generated by Django 3.0.7 on 2020-10-14 06:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201014_0629'),
        ('jobsapp', '0008_auto_20200810_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Applicant creation date and time.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(help_text='Job in applicant.', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobsapp.Job', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(help_text='User applicant.', on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(help_text='Category clasification.', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=models.CharField(help_text='Company description, activity,...', max_length=300, verbose_name='Company description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(help_text="Job's Company name.", max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Job creation date and time.', verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Long job description.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='filled',
            field=models.BooleanField(default=False, help_text='Job position is filled.', verbose_name='Filled'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateTimeField(help_text='Last date.', verbose_name='Last date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(help_text='Location for this job position.', max_length=150, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(blank=True, default=0, help_text='Maximum salary for this job.', verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(help_text='Short job title.', max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Internship')], help_text='Job type.', max_length=10, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(help_text='User who creates this job.', on_delete=django.db.models.deletion.CASCADE, to='accounts.User', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.CharField(default='', help_text='Company Website URL.', max_length=100, verbose_name='Website'),
        ),
    ]
