# Generated by Django 3.0.7 on 2020-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
