# Generated by Django 3.0.7 on 2020-11-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0010_auto_20201107_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['id']},
        ),
    ]
