# Generated by Django 4.0.1 on 2022-10-12 12:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0012_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
