# Generated by Django 5.1.2 on 2026-01-10 14:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0013_job_vacancy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_description',
            field=models.CharField(blank=True, help_text='Legacy field - use company if available', max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, help_text='Legacy field - use company if available', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='website',
            field=models.CharField(blank=True, default='', help_text='Legacy field - use company if available', max_length=100),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, choices=[('1', '1-10 employees'), ('2', '11-50 employees'), ('3', '51-200 employees'), ('4', '201-500 employees'), ('5', '501-1000 employees'), ('6', '1000+ employees')], max_length=20)),
                ('culture_benefits', models.TextField(blank=True, help_text='Describe company culture, benefits, and perks')),
                ('featured', models.BooleanField(default=False, help_text='Feature this company on the homepage')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobsapp.company'),
        ),
    ]
